# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid_upload_path.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url_to_source', models.CharField(blank=True, max_length=200, verbose_name='url to source')),
                ('text_source', models.TextField(blank=True, verbose_name='text source')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'New'), (2, 'Done'), (3, 'Double'), (4, 'Reject'), (5, 'In progress')], verbose_name='status')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='text.Text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uuid_upload_path.storage.upload_to, verbose_name='file')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='sound.Author', verbose_name='author')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sound.Request')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Text', verbose_name='text')),
            ],
        ),
    ]
