# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'New'), (2, 'Done'), (3, 'Double'), (4, 'Reject'), (5, 'In progress')], verbose_name='status')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='text.Text'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sound',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='sound.Author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='text.Text', verbose_name='text'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sound.Request'),
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='taken_by_users',
            field=models.ManyToManyField(related_name='taken_requests', through='sound.ArtistRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
