# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_auto_20161201_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='photo'),
        ),
    ]
