# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0005_auto_20161201_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='taken_by_users',
        ),
        migrations.AddField(
            model_name='artistrequest',
            name='voice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sound.Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistrequest',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'New'), (2, 'Done'), (3, 'Double'), (4, 'Reject'), (5, 'In progress')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Close'), (1, 'New'), (2, 'Done'), (3, 'Double'), (4, 'Reject'), (5, 'In progress')], verbose_name='status'),
        ),
    ]
