# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sound', '0006_auto_20161216_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='taken_by_users',
            field=models.ManyToManyField(related_name='taken_requests', through='sound.ArtistRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
