# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0007_request_taken_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='artistrequest',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'In progress'), (2, 'Done'), (3, 'Double'), (4, 'Reject'), (9, 'Close')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'In progress'), (2, 'Done'), (3, 'Double'), (4, 'Reject'), (9, 'Close')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='taken_by_users',
            field=models.ManyToManyField(related_name='taken_requests', through='sound.ArtistRequest', to='sound.Author'),
        ),
    ]
