# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0008_auto_20161217_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='taken_by_users',
            new_name='taken_by_voices',
        ),
    ]
