# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 14:31
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='photo'),
        ),
    ]
