# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_author_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('text', models.ManyToManyField(related_name='categories', to='text.Text', verbose_name='text')),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='category',
            field=models.ManyToManyField(related_name='texts', to='text.Category', verbose_name='category'),
        ),
    ]
